version: "3.9"

services:
  backend-dev:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "1000:3000"
    volumes:
      - ./backend/servidor:/usr/src/app
    networks:
      - devnet

  front-dev:
    restart: always
    build:
      context: ./fronted
      dockerfile: Dockerfile
    ports:
      - "2000:3000"
    networks:
      - devnet
  
  db-dev:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./baseDatos/local_pgdata_dev:/var/lib/postgresql/data
    networks:
      - devnet

  pgadmin-dev:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dani@dani.com
      PGADMIN_DEFAULT_PASSWORD: "12345"
    volumes:
      - ./baseDatos/pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - devnet

networks:
    devnet:
      driver: bridge
  