version: "3.9"

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  front:
    restart: always
    build:
      context: ./fronted
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
  
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "12345"
    volumes:
      - ./baseDatos/local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container3
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dani@dani.com
      PGADMIN_DEFAULT_PASSWORD: "12345"
    volumes:
      - ./baseDatos/pgadmin-data:/var/lib/pgadmin
  